export const naAmElements: { name: string; element: "Kim"|"Mộc"|"Thủy"|"Hỏa"|"Thổ" }[] = [
  {name:"Hải Trung Kim",     element:"Kim" },{name:"Hải Trung Kim",     element:"Kim" },
  {name:"Lư Trung Hỏa",     element:"Hỏa" },{name:"Lư Trung Hỏa",     element:"Hỏa" },
  {name:"Đại Lâm Mộc",      element:"Mộc" },{name:"Đại Lâm Mộc",      element:"Mộc" },
  {name:"Lộ Bàng Thổ",      element:"Thổ" },{name:"Lộ Bàng Thổ",      element:"Thổ" },
  {name:"Kiếm Phong Kim",    element:"Kim" },{name:"Kiếm Phong Kim",    element:"Kim" },
  {name:"Sơn Đầu Hỏa",      element:"Hỏa" },{name:"Sơn Đầu Hỏa",      element:"Hỏa" },
  {name:"Giản Hạ Thủy",     element:"Thủy"},{name:"Giản Hạ Thủy",     element:"Thủy"},
  {name:"Thành Đầu Thổ",    element:"Thổ" },{name:"Thành Đầu Thổ",    element:"Thổ" },
  {name:"Bạch Lạp Kim",     element:"Kim" },{name:"Bạch Lạp Kim",     element:"Kim" },
  {name:"Dương Liễu Mộc",   element:"Mộc" },{name:"Dương Liễu Mộc",   element:"Mộc" },
  {name:"Tuyền Trung Thủy", element:"Thủy"},{name:"Tuyền Trung Thủy", element:"Thủy"},
  {name:"Ốc Thượng Thổ",   element:"Thổ" },{name:"Ốc Thượng Thổ",   element:"Thổ" },
  {name:"Tích Lịch Hỏa",   element:"Hỏa" },{name:"Tích Lịch Hỏa",   element:"Hỏa" },
  {name:"Tùng Bách Mộc",   element:"Mộc" },{name:"Tùng Bách Mộc",   element:"Mộc" },
  {name:"Trường Lưu Thủy", element:"Thủy"},{name:"Trường Lưu Thủy", element:"Thủy"},
  {name:"Sa Trung Kim",     element:"Kim" },{name:"Sa Trung Kim",     element:"Kim" },
  {name:"Sơn Hạ Hỏa",      element:"Hỏa" },{name:"Sơn Hạ Hỏa",      element:"Hỏa" },
  {name:"Bình Địa Mộc",    element:"Mộc" },{name:"Bình Địa Mộc",    element:"Mộc" },
  {name:"Bích Thượng Thổ", element:"Thổ" },{name:"Bích Thượng Thổ", element:"Thổ" },
  {name:"Kim Bạch Kim",    element:"Kim" },{name:"Kim Bạch Kim",    element:"Kim" },
  {name:"Phú Đăng Hỏa",   element:"Hỏa" },{name:"Phú Đăng Hỏa",   element:"Hỏa" },
  {name:"Thiên Hà Thủy",  element:"Thủy"},{name:"Thiên Hà Thủy",  element:"Thủy"},
  {name:"Đại Trạch Thổ",  element:"Thổ" },{name:"Đại Trạch Thổ",  element:"Thổ" },
  {name:"Thoa Xuyến Kim",  element:"Kim" },{name:"Thoa Xuyến Kim",  element:"Kim" },
  {name:"Tang Đố Mộc",    element:"Mộc" },{name:"Tang Đố Mộc",    element:"Mộc" },
  {name:"Đại Khê Thủy",   element:"Thủy"},{name:"Đại Khê Thủy",   element:"Thủy"},
  {name:"Sa Trung Thổ",   element:"Thổ" },{name:"Sa Trung Thổ",   element:"Thổ" },
  {name:"Thiên Thượng Hỏa",element:"Hỏa"},{name:"Thiên Thượng Hỏa",element:"Hỏa"},
  {name:"Thạch Lựu Mộc",  element:"Mộc" },{name:"Thạch Lựu Mộc",  element:"Mộc" },
  {name:"Đại Hải Thủy",   element:"Thủy"},{name:"Đại Hải Thủy",   element:"Thủy"},
]
